<?php

declare(strict_types=1);

namespace App\Service;

use App\Entity\ServiceProvider;
use App\Entity\Tenant;
use App\Repository\ServiceProviderRepository;
use App\Repository\TenantRepository;
use Psr\Log\LoggerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Lock\LockFactory;

/**
 * Writes SimpleSAMLphp PHP config files dynamically for all active tenants.
 *
 * Files written:
 *  - metadata/saml20-idp-hosted.php   (all active IdPs)
 *  - metadata/saml20-sp-remote.php    (all approved SPs)
 *  - config/authsources.php           (all active authentication backends)
 *
 * The SSP PDO metadata store reads from the database directly.
 * The flatfile store reads these generated PHP files.
 */
class SimpleSamlphpConfigWriter
{
    private readonly Filesystem $fs;

    public function __construct(
        private readonly ServiceProviderRepository $spRepo,
        private readonly TenantRepository          $tenantRepo,
        private readonly LockFactory              $lockFactory,
        private readonly LoggerInterface          $logger,
        private readonly TenantMetadataProfileBuilder $metadataProfileBuilder,
        private readonly string                   $sspConfigDir,
        private readonly string                   $sspMetadataDir,
        private readonly string                   $sspCertDir,
        private readonly string                   $samlidpHostname,
    ) {
        $this->fs = new Filesystem();
    }

    // ─────────────────────────────────────────────────────────
    // IdP-hosted metadata (saml20-idp-hosted.php)
    // ─────────────────────────────────────────────────────────

    public function writeIdpHosted(Tenant $tenant): void
    {
        $lock = $this->lockFactory->createLock('ssp-config-' . $tenant->getSlug(), 30);
        $lock->acquire(true);

        try {
            $tenants = $this->tenantRepo->findAllActive();
            foreach ($tenants as $configuredTenant) {
                $this->writeTenantCert($configuredTenant);
            }

            $blocks = [<<<PHP
<?php
/**
 * AUTO-GENERATED by eduID.africa — do not edit manually.
 * Generated: {$this->now()}
 * Active tenant count: {$this->count($tenants)}
 */
PHP
            ];

            foreach ($tenants as $configuredTenant) {
                $blocks[] = $this->buildIdpHostedBlock($configuredTenant);
            }

            $path = $this->sspMetadataDir . '/saml20-idp-hosted.php';
            $this->writePhpFile($path, implode("\n\n", $blocks), $tenant->getSlug());
        } finally {
            $lock->release();
        }
    }

    // ─────────────────────────────────────────────────────────
    // SP Remote metadata (saml20-sp-remote.php)
    // ─────────────────────────────────────────────────────────

    public function writeSpRemoteMetadata(Tenant $tenant): void
    {
        $lock = $this->lockFactory->createLock('ssp-sp-metadata-' . $tenant->getSlug(), 60);
        $lock->acquire(true);

        try {
            $tenants = $this->tenantRepo->findAllActive();
            $approvedSps = $this->deduplicateServiceProviders(
                $this->spRepo->findApprovedByTenants($tenants)
            );

            $blocks = [];
            $blocks[] = <<<PHP
<?php
/**
 * AUTO-GENERATED SP remote metadata for all active tenants
 * Generated: {$this->now()}
 * SP count: {$this->count($approvedSps)}
 */
PHP;

            foreach ($approvedSps as $sp) {
                $blocks[] = $this->buildSpBlock($sp, $tenant);
            }

            $php  = implode("\n\n", $blocks);
            $path = $this->sspMetadataDir . '/saml20-sp-remote.php';
            $this->writePhpFile($path, $php, $tenant->getSlug());
        } finally {
            $lock->release();
        }
    }

    // ─────────────────────────────────────────────────────────
    // Auth sources (authsources.php)
    // ─────────────────────────────────────────────────────────

    public function writeAuthsource(Tenant $tenant): void
    {
        $tenants = $this->tenantRepo->findAllActive();
        $blocks = [];
        foreach ($tenants as $configuredTenant) {
            $blocks = [...$blocks, ...$this->buildAuthSourceBlocks($configuredTenant)];
        }

        $php = <<<PHP
<?php
/**
 * AUTO-GENERATED authsources for all active tenants
 * Generated: {$this->now()}
 */

\$config = [
    'admin' => [
        'core:AdminPassword',
    ],

{$this->joinBlocks($blocks)}
];
PHP;

        $globalPath = $this->sspConfigDir . '/authsources.php';
        $this->writePhpFile($globalPath, $php, $tenant->getSlug());

        $legacyPath = $this->sspConfigDir . '/authsources-' . $tenant->getSlug() . '.php';
        $legacyBlock = $this->joinBlocks($this->buildAuthSourceBlocks($tenant));
        $legacyPhp = <<<PHP
<?php
/**
 * AUTO-GENERATED authsources for tenant: {$tenant->getName()} ({$tenant->getSlug()})
 * Generated: {$this->now()}
 */

\$config = [
    'admin' => [
        'core:AdminPassword',
    ],

{$legacyBlock}
];
PHP;
        $this->writePhpFile($legacyPath, $legacyPhp, $tenant->getSlug());
    }

    // ─────────────────────────────────────────────────────────
    // PRIVATE BUILDERS
    // ─────────────────────────────────────────────────────────

    private function buildSpBlock(ServiceProvider $sp, Tenant $tenant): string
    {
        $entityId = addslashes($sp->getEntityId());
        $name     = addslashes($sp->getDisplayName());
        $acsUrl   = trim((string) ($sp->getAcsUrl() ?? ''));
        $sloUrl   = trim((string) ($sp->getSloUrl() ?? ''));

        if ($acsUrl === '') {
            $this->logger->warning('Skipping SP metadata block without ACS URL', [
                'entity_id' => $sp->getEntityId(),
                'tenant' => $tenant->getSlug(),
            ]);

            return <<<PHP
// Skipped SP {$name} ({$entityId}) because no AssertionConsumerService URL is configured.
PHP;
        }

        // Attribute release
        $attrs = $sp->getAttributeReleaseOverride()
            ?? ($tenant->getAttributeReleasePolicy()['default'] ?? null)
            ?? $this->getDefaultAttributes($tenant);

        $attrsPhp = $this->phpArrayLiteral($attrs);

        $nameIdFormat = addslashes($sp->getNameIdFormat());
        $acsUrlEscaped = addslashes($acsUrl);
        $sloSection = '';
        if ($sloUrl !== '') {
            $sloUrlEscaped = addslashes($sloUrl);
            $sloSection = <<<PHP
    'SingleLogoutService' => [
        [
            'Binding'   => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location'  => '{$sloUrlEscaped}',
        ],
    ],
PHP;
        }

        // Certificate handling
        $certLine = '';
        if ($sp->getCertificate()) {
            $cert     = addslashes($sp->getCertificate());
            $certLine = "'certData' => '{$cert}',";
        }

        $encryptLine = $sp->isEncryptAssertions()
            ? "'assertion.encryption' => true,"
            : "'assertion.encryption' => false,";

        return <<<PHP
\$metadata['{$entityId}'] = [
    // SP: {$name}
    'AssertionConsumerService' => [
        [
            'Binding'   => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location'  => '{$acsUrlEscaped}',
            'index'     => 1,
        ],
    ],
{$sloSection}
    'NameIDFormat'     => '{$nameIdFormat}',
    {$certLine}
    {$encryptLine}
    'sign.authnrequest' => true,
    'attributes'       => {$attrsPhp},
    'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
    'authproc'         => [],
];
PHP;
    }

    /**
     * SimpleSAMLphp remote metadata is keyed globally by entityID, so later
     * duplicate blocks overwrite earlier ones. Prefer the most complete row.
     *
     * @param ServiceProvider[] $serviceProviders
     *
     * @return ServiceProvider[]
     */
    private function deduplicateServiceProviders(array $serviceProviders): array
    {
        $selected = [];

        foreach ($serviceProviders as $serviceProvider) {
            $entityId = trim($serviceProvider->getEntityId());
            if ($entityId === '') {
                continue;
            }

            $current = $selected[$entityId] ?? null;
            if ($current === null || $this->scoreServiceProvider($serviceProvider) > $this->scoreServiceProvider($current)) {
                if ($current !== null) {
                    $this->logger->warning('Replacing duplicate SP metadata entry with better candidate.', [
                        'entity_id' => $entityId,
                        'kept_source' => $serviceProvider->getSource(),
                        'replaced_source' => $current->getSource(),
                        'kept_tenant' => $serviceProvider->getTenant()?->getSlug(),
                        'replaced_tenant' => $current->getTenant()?->getSlug(),
                    ]);
                }

                $selected[$entityId] = $serviceProvider;
            }
        }

        uasort($selected, static fn (ServiceProvider $left, ServiceProvider $right): int => strcmp(
            $left->getDisplayName(),
            $right->getDisplayName()
        ));

        return array_values($selected);
    }

    private function scoreServiceProvider(ServiceProvider $serviceProvider): int
    {
        $score = 0;

        $sourceScore = match ($serviceProvider->getSource()) {
            ServiceProvider::SOURCE_MANUAL => 1000,
            ServiceProvider::SOURCE_EDUGAIN => 500,
            ServiceProvider::SOURCE_METADATA => 250,
            default => 0,
        };

        $score += $sourceScore;
        $score += $this->hasValue($serviceProvider->getAcsUrl()) ? 200 : 0;
        $score += $this->hasValue($serviceProvider->getSloUrl()) ? 100 : 0;
        $score += $this->hasValue($serviceProvider->getCertificate()) ? 50 : 0;
        $score += $this->hasValue($serviceProvider->getName()) ? 25 : 0;
        $score += count($serviceProvider->getRequestedAttributes() ?? []) > 0 ? 10 : 0;

        return $score;
    }

    private function hasValue(?string $value): bool
    {
        return trim((string) $value) !== '';
    }

    private function buildLdapAuthSource(Tenant $tenant, string $name): string
    {
        $cfg = $tenant->getLdapConfig() ?? [];

        $host          = addslashes($cfg['host']          ?? 'ldap://localhost');
        $baseDn        = addslashes($cfg['base_dn']       ?? 'dc=example,dc=com');
        $bindDn        = addslashes($cfg['bind_dn']       ?? '');
        $bindPw        = addslashes($cfg['bind_password'] ?? '');
        $userAttr      = addslashes($cfg['user_attr']     ?? 'uid');
        $searchFilter  = addslashes($cfg['search_filter'] ?? '(&(objectClass=person)(%username%))');
        $dnPattern     = addslashes($cfg['dn_pattern']    ?? '');
        $timeout       = (int) ($cfg['timeout'] ?? 30);
        $startTls      = ($cfg['start_tls'] ?? false) ? 'true' : 'false';

        // Build attribute map
        $attrMapPhp = $this->phpArrayLiteral($cfg['attribute_map'] ?? [
            'uid'                         => ['uid'],
            'mail'                        => ['mail'],
            'cn'                          => ['cn'],
            'sn'                          => ['sn'],
            'givenName'                   => ['givenName'],
            'displayName'                 => ['displayName'],
            'eduPersonPrincipalName'      => ['eduPersonPrincipalName'],
            'eduPersonAffiliation'        => ['eduPersonAffiliation'],
            'eduPersonScopedAffiliation'  => ['eduPersonScopedAffiliation'],
            'eduPersonEntitlement'        => ['eduPersonEntitlement'],
            'schacHomeOrganization'       => ['schacHomeOrganization'],
        ]);

        return <<<PHP
    '{$name}' => [
        'ubuntunet:Ldap',
        'tenant_slug'       => '{$tenant->getSlug()}',
        'connection_string' => '{$host}',
        'encryption'        => '{$startTls}' === 'true' ? 'starttls' : 'none',
        'version'           => 3,
        'timeout'           => {$timeout},
        'referrals'         => false,

        'searchBase'        => '{$baseDn}',
        'searchFilter'      => '{$searchFilter}',
        'searchAttributes'  => false,
        'dnPattern'         => '{$dnPattern}',
        'attribute'         => '{$userAttr}',

        'username'          => '{$bindDn}',
        'password'          => '{$bindPw}',

        'attributes'        => {$attrMapPhp},
    ],
PHP;
    }

    private function buildSamlAuthSource(Tenant $tenant, string $name): string
    {
        $cfg = $tenant->getSamlUpstreamConfig() ?? [];

        $upstreamIdp    = addslashes($cfg['idp_entity_id']  ?? '');
        $metadataUrl    = addslashes($cfg['metadata_url']   ?? '');
        $discoUrl       = addslashes($cfg['discovery_url']  ?? '');

        if ($upstreamIdp === '' && $metadataUrl === '') {
            throw new \InvalidArgumentException(sprintf(
                'Tenant "%s" uses the SAML Proxy backend but has no upstream metadata URL or IdP entity ID configured.',
                $tenant->getSlug()
            ));
        }

        return <<<PHP
    '{$name}' => [
        'saml:SP',
        'entityID'       => null,   // use SSP's own entity ID
        'idp'            => '{$upstreamIdp}' ?: null,
        'discoURL'       => '{$discoUrl}' ?: null,
        'metadataURL'    => '{$metadataUrl}' ?: null,

        'privatekey'     => 'wildcard_certificate.key',
        'certificate'    => 'wildcard_certificate.crt',

        'sign.authnrequest' => true,
        'sign.logout'       => true,
    ],
PHP;
    }

    /**
     * @return string[]
     */
    private function buildAuthSourceBlocks(Tenant $tenant): array
    {
        $authSourceName = 'idp-' . $tenant->getSlug();

        return match ($tenant->getAuthType()) {
            Tenant::AUTH_LDAP     => [$this->buildLdapAuthSource($tenant, $authSourceName)],
            Tenant::AUTH_SAML     => $this->buildBrokeredSamlAuthSources($tenant, $authSourceName),
            Tenant::AUTH_USERPASS => [$this->buildUserpassAuthSource($tenant, $authSourceName)],
            Tenant::AUTH_DATABASE => [$this->buildUserpassAuthSource($tenant, $authSourceName)],
            Tenant::AUTH_RADIUS   => [$this->buildRadiusAuthSource($tenant, $authSourceName)],
            default               => throw new \InvalidArgumentException('Unknown auth type: ' . $tenant->getAuthType()),
        };
    }

    /**
     * @return string[]
     */
    private function buildBrokeredSamlAuthSources(Tenant $tenant, string $name): array
    {
        $cfg = $tenant->getSamlUpstreamConfig() ?? [];
        $methods = $this->getEnabledBrokerMethods($cfg);

        if ($methods === []) {
            return [$this->buildSamlAuthSource($tenant, $name)];
        }

        if (count($methods) === 1) {
            return [$this->buildBrokerMethodBlock($tenant, $name, $methods[0])];
        }

        $blocks = [];
        $sources = [];
        foreach ($methods as $method) {
            $methodName = $this->buildBrokerMethodName($name, $method);
            $blocks[] = $this->buildBrokerMethodBlock($tenant, $methodName, $method);
            $sources[$methodName] = [
                'text' => $this->normalizeBrokerLabel($method, $this->defaultBrokerLabel($method)),
            ];
        }

        $blocks[] = $this->buildMultiAuthSource($name, $sources, $cfg['preselect'] ?? null);

        return $blocks;
    }

    /**
     * @param array<string, mixed> $method
     */
    private function buildBrokerMethodBlock(Tenant $tenant, string $name, array $method): string
    {
        return match ($method['type'] ?? null) {
            'local' => $this->buildUserpassAuthSource($tenant, $name),
            'saml' => $this->buildUpstreamSamlMethodAuthSource($name, $method),
            'oidc' => $this->buildOidcMethodAuthSource($name, $method),
            default => throw new \InvalidArgumentException(sprintf(
                'Tenant "%s" uses an unsupported broker method type "%s".',
                $tenant->getSlug(),
                (string) ($method['type'] ?? '')
            )),
        };
    }

    /**
     * @param array<string, array<string, mixed>> $sources
     */
    private function buildMultiAuthSource(string $name, array $sources, mixed $preselect = null): string
    {
        $preselectLine = '';
        if (is_string($preselect) && trim($preselect) !== '') {
            $preselectName = $this->buildBrokerMethodName($name, ['key' => trim($preselect)]);
            $preselectLine = "        'preselect' => '" . addslashes($preselectName) . "',\n";
        }

        return <<<PHP
    '{$name}' => [
        'multiauth:MultiAuth',
        'sources' => {$this->phpArrayLiteral($sources)},
{$preselectLine}    ],
PHP;
    }

    /**
     * @param array<string, mixed> $method
     */
    private function buildUpstreamSamlMethodAuthSource(string $name, array $method): string
    {
        $upstreamIdp = addslashes(trim((string) ($method['idp_entity_id'] ?? '')));
        $metadataUrl = addslashes(trim((string) ($method['metadata_url'] ?? '')));
        $discoUrl = addslashes(trim((string) ($method['discovery_url'] ?? '')));

        if ($upstreamIdp === '' && $metadataUrl === '') {
            throw new \InvalidArgumentException('Broker SAML method requires "metadata_url" or "idp_entity_id".');
        }

        return <<<PHP
    '{$name}' => [
        'saml:SP',
        'entityID'       => null,
        'idp'            => '{$upstreamIdp}' ?: null,
        'discoURL'       => '{$discoUrl}' ?: null,
        'metadataURL'    => '{$metadataUrl}' ?: null,
        'privatekey'     => 'wildcard_certificate.key',
        'certificate'    => 'wildcard_certificate.crt',
        'sign.authnrequest' => true,
        'sign.logout'       => true,
    ],
PHP;
    }

    /**
     * @param array<string, mixed> $method
     */
    private function buildOidcMethodAuthSource(string $name, array $method): string
    {
        $providerName = addslashes(trim((string) ($method['provider_name'] ?? $this->defaultBrokerLabel($method))));
        $issuer = addslashes(rtrim(trim((string) ($method['issuer'] ?? '')), '/'));
        $clientId = addslashes(trim((string) ($method['client_id'] ?? '')));
        $clientSecret = addslashes(trim((string) ($method['client_secret'] ?? '')));
        $clientAuthMethod = addslashes(trim((string) ($method['client_auth_method'] ?? 'client_secret_post')));
        $prompt = addslashes(trim((string) ($method['prompt'] ?? '')));
        $loginHint = addslashes(trim((string) ($method['login_hint'] ?? '')));
        $authorizationEndpoint = addslashes(trim((string) ($method['authorization_endpoint'] ?? '')));
        $tokenEndpoint = addslashes(trim((string) ($method['token_endpoint'] ?? '')));
        $userinfoEndpoint = addslashes(trim((string) ($method['userinfo_endpoint'] ?? '')));
        $jwksUri = addslashes(trim((string) ($method['jwks_uri'] ?? '')));
        $scopes = $this->phpArrayLiteral($method['scopes'] ?? ['openid', 'email', 'profile']);
        $attributeMap = $this->phpArrayLiteral($method['attribute_map'] ?? $this->getDefaultOidcAttributeMap());

        if ($clientId === '' || $clientSecret === '') {
            throw new \InvalidArgumentException('Broker OIDC method requires "client_id" and "client_secret".');
        }

        return <<<PHP
    '{$name}' => [
        'ubuntunetbroker:OidcGeneric',
        'provider_name' => '{$providerName}',
        'issuer' => '{$issuer}',
        'client_id' => '{$clientId}',
        'client_secret' => '{$clientSecret}',
        'client_auth_method' => '{$clientAuthMethod}',
        'prompt' => '{$prompt}',
        'login_hint' => '{$loginHint}',
        'authorization_endpoint' => '{$authorizationEndpoint}',
        'token_endpoint' => '{$tokenEndpoint}',
        'userinfo_endpoint' => '{$userinfoEndpoint}',
        'jwks_uri' => '{$jwksUri}',
        'scopes' => {$scopes},
        'attribute_map' => {$attributeMap},
    ],
PHP;
    }

    private function buildUserpassAuthSource(Tenant $tenant, string $name): string
    {
        // Builds a database-backed auth source using our custom ubuntunet module
        $slug = $tenant->getSlug();
        return <<<PHP
    '{$name}' => [
        'ubuntunet:DatabaseAuth',
        'tenant_slug' => '{$slug}',
    ],
PHP;
    }

    private function buildRadiusAuthSource(Tenant $tenant, string $name): string
    {
        $cfg    = $tenant->getRadiusConfig() ?? [];
        $server = addslashes($cfg['server'] ?? '127.0.0.1');
        $secret = addslashes($cfg['secret'] ?? '');
        $port   = (int) ($cfg['port'] ?? 1812);

        return <<<PHP
    '{$name}' => [
        'radius:Radius',
        'hostname' => '{$server}',
        'secret'   => '{$secret}',
        'port'     => {$port},
        'timeout'  => 30,
        'retries'  => 3,
        'realm'    => '',
        'nas_identifier' => '{$this->samlidpHostname}',
    ],
PHP;
    }

    private function writeTenantCert(Tenant $tenant): void
    {
        $slug    = $tenant->getSlug();
        $certPem = $tenant->getSigningCertificate();
        $keyPem  = $tenant->getSigningPrivateKey();

        if (empty($certPem) || empty($keyPem)) {
            // Fall back to wildcard cert
            return;
        }

        $normalizedCert = preg_replace('/\s+/', '', trim($certPem));

        // Write cert with headers
        $certFormatted  = "-----BEGIN CERTIFICATE-----\n";
        $certFormatted .= chunk_split($normalizedCert, 64, "\n");
        $certFormatted .= "-----END CERTIFICATE-----\n";

        $this->fs->dumpFile($this->sspCertDir . '/' . $slug . '.crt', $certFormatted);
        $this->fs->dumpFile($this->sspCertDir . '/' . $slug . '.pem', $keyPem);
        $this->normalizeOwnership(
            $this->sspCertDir . '/' . $slug . '.crt',
            $this->sspCertDir . '/' . $slug . '.pem',
        );
        $this->fs->chmod($this->sspCertDir . '/' . $slug . '.crt', 0644);
        $this->fs->chmod($this->sspCertDir . '/' . $slug . '.pem', 0600);
    }

    private function writePhpFile(string $path, string $content, string $tenantSlug): void
    {
        // Write to a temp file first, then atomic rename
        $tmp = $path . '.tmp.' . $tenantSlug . '.' . getmypid();
        $this->fs->dumpFile($tmp, $content);

        // Lightweight syntax validation. Requiring large generated metadata files can
        // exhaust memory because PHP executes all array assignments during validation.
        try {
            token_get_all($content, \TOKEN_PARSE);
        } catch (\ParseError $e) {
            $this->fs->remove($tmp);
            throw new \RuntimeException(
                sprintf('Generated PHP file has syntax errors for tenant %s: %s', $tenantSlug, $e->getMessage()),
                previous: $e,
            );
        }

        $this->fs->rename($tmp, $path, true);
        $this->normalizeOwnership($path);
        $this->logger->debug('Written SSP config file', ['path' => $path, 'tenant' => $tenantSlug]);
    }

    private function getDefaultAttributes(Tenant $tenant): array
    {
        $policy = $tenant->getAttributeReleasePolicy();
        return $policy['default'] ?? [
            'uid',
            'mail',
            'cn',
            'sn',
            'givenName',
            'displayName',
            'eduPersonPrincipalName',
            'eduPersonAffiliation',
            'eduPersonScopedAffiliation',
            'eduPersonEntitlement',
            'eduPersonTargetedID',
            'isMemberOf',
            'preferredLanguage',
            'copAccessGroup',
            'copFunctionalGroup',
            'copInstitutionalGroup',
            'schacHomeOrganization',
        ];
    }

    /**
     * @param array<string, mixed> $cfg
     * @return array<int, array<string, mixed>>
     */
    private function getEnabledBrokerMethods(array $cfg): array
    {
        $methods = $cfg['methods'] ?? null;
        if (!is_array($methods)) {
            return [];
        }

        $enabled = [];
        foreach ($methods as $index => $method) {
            if (!is_array($method)) {
                continue;
            }

            if (($method['enabled'] ?? true) === false) {
                continue;
            }

            $type = trim((string) ($method['type'] ?? ''));
            if ($type === '') {
                continue;
            }

            if (!isset($method['key']) || trim((string) $method['key']) === '') {
                $method['key'] = $type . '-' . ($index + 1);
            }

            $enabled[] = $method;
        }

        return $enabled;
    }

    /**
     * @param array<string, mixed> $method
     */
    private function buildBrokerMethodName(string $rootName, array $method): string
    {
        $key = strtolower(trim((string) ($method['key'] ?? 'method')));
        $key = preg_replace('/[^a-z0-9]+/', '-', $key) ?: 'method';
        $key = trim($key, '-');

        return $rootName . '--' . $key;
    }

    /**
     * @param array<string, mixed> $method
     * @return array<string, string>
     */
    private function normalizeBrokerLabel(array $method, string $fallback): array
    {
        $label = $method['label'] ?? $method['text'] ?? null;
        if (is_array($label) && $label !== []) {
            $normalized = [];
            foreach ($label as $locale => $value) {
                $locale = trim((string) $locale);
                $value = trim((string) $value);
                if ($locale !== '' && $value !== '') {
                    $normalized[$locale] = $value;
                }
            }
            if ($normalized !== []) {
                return $normalized;
            }
        }

        if (is_string($label) && trim($label) !== '') {
            return ['en' => trim($label)];
        }

        return ['en' => $fallback];
    }

    /**
     * @param array<string, mixed> $method
     */
    private function defaultBrokerLabel(array $method): string
    {
        $provider = trim((string) ($method['provider_name'] ?? ''));
        if ($provider !== '') {
            return $provider;
        }

        return match (trim((string) ($method['type'] ?? ''))) {
            'local' => 'UbuntuNet account',
            'saml' => 'Institutional login',
            'oidc' => 'Social login',
            default => 'Sign in',
        };
    }

    private function getBrokerProfile(Tenant $tenant): array
    {
        $cfg = $tenant->getSamlUpstreamConfig() ?? [];
        $profile = is_array($cfg['broker_profile'] ?? null) ? $cfg['broker_profile'] : [];
        $defaultScope = trim((string) ($profile['default_scope'] ?? ''));

        return [
            'default_scope' => $defaultScope !== '' ? $defaultScope : $tenant->getSlug() . '.' . $this->samlidpHostname,
            'identifier_salt' => trim((string) ($profile['identifier_salt'] ?? getenv('BROKER_IDENTIFIER_SALT') ?: 'change-me-before-production')),
            'affiliation' => $profile['affiliation'] ?? ['member'],
            'groups' => $profile['groups'] ?? [],
            'entitlements' => $profile['entitlements'] ?? [],
            'languages' => $profile['languages'] ?? [],
            'access_groups' => $profile['access_groups'] ?? [],
            'functional_groups' => $profile['functional_groups'] ?? [],
            'institutional_groups' => $profile['institutional_groups'] ?? [],
        ];
    }

    private function getDefaultOidcAttributeMap(): array
    {
        return [
            'sub' => ['uid', 'oidc_sub'],
            'email' => ['mail'],
            'name' => ['displayName', 'display_name', 'cn'],
            'given_name' => ['givenName'],
            'family_name' => ['sn', 'surName'],
            'preferred_username' => ['username'],
            'locale' => ['preferredLanguage'],
            'hd' => ['schacHomeOrganization'],
        ];
    }

    private function phpArrayLiteral(array $arr): string
    {
        if (empty($arr)) {
            return '[]';
        }

        $items = [];
        foreach ($arr as $key => $value) {
            $renderedValue = $this->phpValueLiteral($value);

            if (is_int($key)) {
                $items[] = $renderedValue;
                continue;
            }

            $items[] = "'" . addslashes((string) $key) . "' => " . $renderedValue;
        }

        return '[' . implode(', ', $items) . ']';
    }

    private function phpValueLiteral(mixed $value): string
    {
        if (is_array($value)) {
            return $this->phpArrayLiteral($value);
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        if ($value === null) {
            return 'null';
        }

        return "'" . addslashes((string) $value) . "'";
    }

    private function now(): string
    {
        return (new \DateTimeImmutable())->format('Y-m-d H:i:s T');
    }

    private function count(array $arr): int
    {
        return count($arr);
    }

    /**
     * @param string[] $blocks
     */
    private function joinBlocks(array $blocks): string
    {
        return implode("\n\n", array_filter($blocks));
    }

    private function normalizeOwnership(string ...$paths): void
    {
        if (!function_exists('posix_geteuid') || posix_geteuid() !== 0) {
            return;
        }

        foreach ($paths as $path) {
            if (!file_exists($path)) {
                continue;
            }

            @chown($path, 'app');
            @chgrp($path, 'app');
        }
    }

    private function buildIdpHostedBlock(Tenant $tenant): string
    {
        $entityId = addslashes($tenant->getEntityId());
        $slug     = addslashes($tenant->getSlug());
        $certFile = $slug . '.crt';
        $keyFile  = $slug . '.pem';
        $authSourceName = 'idp-' . $slug;
        $ssoUrl = "https://{$slug}.{$this->samlidpHostname}/saml2/idp/SSOService.php";
        $sloUrl = "https://{$slug}.{$this->samlidpHostname}/saml2/idp/SingleLogoutService.php";

        $mfaOptions = match ($tenant->getMfaPolicy()) {
            'required' => "'requireMFA' => true,",
            'optional' => "'requireMFA' => false,",
            default    => '',
        };

        $metadata = $this->metadataProfileBuilder->build($tenant);
        $hostedUiInfo = $this->normalizeHostedUiInfo($metadata['ui_info'] ?? []);
        $hostedRegistrationInfo = $this->normalizeHostedRegistrationInfo($metadata['registration_info'] ?? []);
        $orgName = addslashes($metadata['organization_name']);
        $orgUrl  = addslashes($metadata['organization_url']);
        $authProcLines = $this->buildHostedAuthProcLines($tenant);
        $contactSection = $metadata['contacts'] === []
            ? ''
            : "    'contacts' => " . $this->phpArrayLiteral($metadata['contacts']) . ",\n";
        $registrationInfoSection = $hostedRegistrationInfo === []
            ? ''
            : "    'RegistrationInfo' => " . $this->phpArrayLiteral($hostedRegistrationInfo) . ",\n";
        $discoHintsSection = $metadata['disco_hints'] === []
            ? ''
            : "    'DiscoHints' => " . $this->phpArrayLiteral($metadata['disco_hints']) . ",\n";

        return <<<PHP
\$metadata['{$entityId}'] = [
    'host'           => '{$slug}.{$this->samlidpHostname}',
    'privatekey'     => '{$keyFile}',
    'certificate'    => '{$certFile}',
    'metadata.sign.privatekey' => '{$keyFile}',
    'metadata.sign.certificate' => '{$certFile}',
    'auth'           => '{$authSourceName}',
    'scope'          => ['{$slug}.{$this->samlidpHostname}'],
    'entityid'       => '{$entityId}',
    'SingleSignOnService' => '{$ssoUrl}',
    'SingleLogoutService' => '{$sloUrl}',
    'signature.algorithm'         => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
    'metadata.sign.enable'        => true,
    'metadata.sign.algorithm'     => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
    'assertion.encryption'        => false,
    'SingleLogoutServiceBinding' => [
        'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
    ],
    'NameIDFormat'   => [
        'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
    ],
    'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
    'authproc' => [
{$authProcLines}    ],
    'OrganizationName'        => ['en' => '{$orgName}'],
    'OrganizationDisplayName' => ['en' => '{$orgName}'],
    'OrganizationURL'         => ['en' => '{$orgUrl}'],
{$contactSection}{$registrationInfoSection}    'UIInfo' => {$this->phpArrayLiteral($hostedUiInfo)},
{$discoHintsSection}
    {$mfaOptions}
];
PHP;
    }

    private function normalizeHostedRegistrationInfo(array $registrationInfo): array
    {
        if ($registrationInfo === []) {
            return [];
        }

        $normalized = [];

        if (!empty($registrationInfo['RegistrationAuthority']) && is_string($registrationInfo['RegistrationAuthority'])) {
            $normalized['authority'] = $registrationInfo['RegistrationAuthority'];
        }

        if (!empty($registrationInfo['RegistrationInstant']) && is_string($registrationInfo['RegistrationInstant'])) {
            $normalized['instant'] = $registrationInfo['RegistrationInstant'];
        }

        if (!empty($registrationInfo['RegistrationPolicy']) && is_array($registrationInfo['RegistrationPolicy'])) {
            $normalized['policies'] = $registrationInfo['RegistrationPolicy'];
        }

        return $normalized;
    }

    private function normalizeHostedUiInfo(array $uiInfo): array
    {
        if ($uiInfo === []) {
            return [];
        }

        if (!isset($uiInfo['Logo']) || !is_array($uiInfo['Logo'])) {
            return $uiInfo;
        }

        $uiInfo['Logo'] = array_map(function (mixed $logo): mixed {
            if (!is_array($logo)) {
                return $logo;
            }

            if (array_key_exists('width', $logo)) {
                $logo['width'] = (int) $logo['width'];
            }

            if (array_key_exists('height', $logo)) {
                $logo['height'] = (int) $logo['height'];
            }

            return $logo;
        }, $uiInfo['Logo']);

        return $uiInfo;
    }

    private function buildHostedAuthProcLines(Tenant $tenant): string
    {
        $lines = [];

        if ($tenant->getAuthType() === Tenant::AUTH_SAML && $this->getEnabledBrokerMethods($tenant->getSamlUpstreamConfig() ?? []) !== []) {
            $profile = $this->getBrokerProfile($tenant);
            $lines[] = "        5 => [\n"
                . "            'class' => 'ubuntunetbroker:AttributeAugment',\n"
                . "            'idp' => '" . addslashes($tenant->getSlug()) . "',\n"
                . "            'scope' => '" . addslashes((string) $profile['default_scope']) . "',\n"
                . "            'identifier_salt' => '" . addslashes((string) $profile['identifier_salt']) . "',\n"
                . "            'affiliation' => " . $this->phpArrayLiteral((array) $profile['affiliation']) . ",\n"
                . "            'groups' => " . $this->phpArrayLiteral((array) $profile['groups']) . ",\n"
                . "            'entitlements' => " . $this->phpArrayLiteral((array) $profile['entitlements']) . ",\n"
                . "            'languages' => " . $this->phpArrayLiteral((array) $profile['languages']) . ",\n"
                . "            'access_groups' => " . $this->phpArrayLiteral((array) $profile['access_groups']) . ",\n"
                . "            'functional_groups' => " . $this->phpArrayLiteral((array) $profile['functional_groups']) . ",\n"
                . "            'institutional_groups' => " . $this->phpArrayLiteral((array) $profile['institutional_groups']) . ",\n"
                . "        ],";
        }

        $lines[] = "        20 => [\n"
            . "            'class' => 'saml:PersistentNameID',\n"
            . "            'identifyingAttribute' => 'eduPersonPrincipalName',\n"
            . "        ],";
        $lines[] = "        30 => [\n"
            . "            'class' => 'saml:PersistentNameID2TargetedID',\n"
            . "            'attribute' => 'eduPersonTargetedID',\n"
            . "            'nameId' => false,\n"
            . "        ],";
        $lines[] = "        70 => [\n"
            . "            'class'   => 'core:AttributeLimit',\n"
            . "            'default' => " . $this->phpArrayLiteral($this->getDefaultAttributes($tenant)) . ",\n"
            . "        ],";
        $lines[] = "        80 => [\n"
            . "            'class' => 'core:AttributeMap',\n"
            . "            'name2oid',\n"
            . "            '%duplicate',\n"
            . "        ],";

        return implode("\n", $lines) . "\n";
    }
}
