<?php

declare(strict_types=1);

namespace App\Service;

use App\Entity\ServiceProvider;
use App\Entity\Tenant;
use App\Repository\ServiceProviderRepository;
use App\Repository\TenantRepository;
use Psr\Log\LoggerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Lock\LockFactory;

/**
 * Writes SimpleSAMLphp PHP config files dynamically for all active tenants.
 *
 * Files written:
 *  - metadata/saml20-idp-hosted.php   (all active IdPs)
 *  - metadata/saml20-sp-remote.php    (all approved SPs)
 *  - config/authsources.php           (all active authentication backends)
 *
 * The SSP PDO metadata store reads from the database directly.
 * The flatfile store reads these generated PHP files.
 */
class SimpleSamlphpConfigWriter
{
    private readonly Filesystem $fs;

    public function __construct(
        private readonly ServiceProviderRepository $spRepo,
        private readonly TenantRepository          $tenantRepo,
        private readonly LockFactory              $lockFactory,
        private readonly LoggerInterface          $logger,
        private readonly TenantMetadataProfileBuilder $metadataProfileBuilder,
        private readonly string                   $sspConfigDir,
        private readonly string                   $sspMetadataDir,
        private readonly string                   $sspCertDir,
        private readonly string                   $samlidpHostname,
    ) {
        $this->fs = new Filesystem();
    }

    // ─────────────────────────────────────────────────────────
    // IdP-hosted metadata (saml20-idp-hosted.php)
    // ─────────────────────────────────────────────────────────

    public function writeIdpHosted(Tenant $tenant): void
    {
        $lock = $this->lockFactory->createLock('ssp-config-' . $tenant->getSlug(), 30);
        $lock->acquire(true);

        try {
            $tenants = $this->tenantRepo->findAllActive();
            foreach ($tenants as $configuredTenant) {
                $this->writeTenantCert($configuredTenant);
            }

            $blocks = [<<<PHP
<?php
/**
 * AUTO-GENERATED by eduID.africa — do not edit manually.
 * Generated: {$this->now()}
 * Active tenant count: {$this->count($tenants)}
 */
PHP
            ];

            foreach ($tenants as $configuredTenant) {
                $blocks[] = $this->buildIdpHostedBlock($configuredTenant);
            }

            $path = $this->sspMetadataDir . '/saml20-idp-hosted.php';
            $this->writePhpFile($path, implode("\n\n", $blocks), $tenant->getSlug());
        } finally {
            $lock->release();
        }
    }

    // ─────────────────────────────────────────────────────────
    // SP Remote metadata (saml20-sp-remote.php)
    // ─────────────────────────────────────────────────────────

    public function writeSpRemoteMetadata(Tenant $tenant): void
    {
        $lock = $this->lockFactory->createLock('ssp-sp-metadata-' . $tenant->getSlug(), 60);
        $lock->acquire(true);

        try {
            $tenants = $this->tenantRepo->findAllActive();
            $approvedSps = $this->deduplicateServiceProviders(
                $this->spRepo->findApprovedByTenants($tenants)
            );

            $blocks = [];
            $blocks[] = <<<PHP
<?php
/**
 * AUTO-GENERATED SP remote metadata for all active tenants
 * Generated: {$this->now()}
 * SP count: {$this->count($approvedSps)}
 */
PHP;

            foreach ($approvedSps as $sp) {
                $blocks[] = $this->buildSpBlock($sp, $tenant);
            }

            $php  = implode("\n\n", $blocks);
            $path = $this->sspMetadataDir . '/saml20-sp-remote.php';
            $this->writePhpFile($path, $php, $tenant->getSlug());
        } finally {
            $lock->release();
        }
    }

    // ─────────────────────────────────────────────────────────
    // Auth sources (authsources.php)
    // ─────────────────────────────────────────────────────────

    public function writeAuthsource(Tenant $tenant): void
    {
        $tenants = $this->tenantRepo->findAllActive();
        $blocks = [];
        foreach ($tenants as $configuredTenant) {
            $authSourceName = 'idp-' . $configuredTenant->getSlug();
            $blocks[] = match ($configuredTenant->getAuthType()) {
                Tenant::AUTH_LDAP     => $this->buildLdapAuthSource($configuredTenant, $authSourceName),
                Tenant::AUTH_SAML     => $this->buildSamlAuthSource($configuredTenant, $authSourceName),
                Tenant::AUTH_USERPASS => $this->buildUserpassAuthSource($configuredTenant, $authSourceName),
                Tenant::AUTH_DATABASE => $this->buildUserpassAuthSource($configuredTenant, $authSourceName),
                Tenant::AUTH_RADIUS   => $this->buildRadiusAuthSource($configuredTenant, $authSourceName),
                default               => throw new \InvalidArgumentException('Unknown auth type: ' . $configuredTenant->getAuthType()),
            };
        }

        $php = <<<PHP
<?php
/**
 * AUTO-GENERATED authsources for all active tenants
 * Generated: {$this->now()}
 */

\$config = [
    'admin' => [
        'core:AdminPassword',
    ],

{$this->joinBlocks($blocks)}
];
PHP;

        $globalPath = $this->sspConfigDir . '/authsources.php';
        $this->writePhpFile($globalPath, $php, $tenant->getSlug());

        $legacyPath = $this->sspConfigDir . '/authsources-' . $tenant->getSlug() . '.php';
        $legacyBlock = match ($tenant->getAuthType()) {
            Tenant::AUTH_LDAP     => $this->buildLdapAuthSource($tenant, 'idp-' . $tenant->getSlug()),
            Tenant::AUTH_SAML     => $this->buildSamlAuthSource($tenant, 'idp-' . $tenant->getSlug()),
            Tenant::AUTH_USERPASS => $this->buildUserpassAuthSource($tenant, 'idp-' . $tenant->getSlug()),
            Tenant::AUTH_DATABASE => $this->buildUserpassAuthSource($tenant, 'idp-' . $tenant->getSlug()),
            Tenant::AUTH_RADIUS   => $this->buildRadiusAuthSource($tenant, 'idp-' . $tenant->getSlug()),
            default               => throw new \InvalidArgumentException('Unknown auth type: ' . $tenant->getAuthType()),
        };
        $legacyPhp = <<<PHP
<?php
/**
 * AUTO-GENERATED authsources for tenant: {$tenant->getName()} ({$tenant->getSlug()})
 * Generated: {$this->now()}
 */

\$config = [
    'admin' => [
        'core:AdminPassword',
    ],

{$legacyBlock}
];
PHP;
        $this->writePhpFile($legacyPath, $legacyPhp, $tenant->getSlug());
    }

    // ─────────────────────────────────────────────────────────
    // PRIVATE BUILDERS
    // ─────────────────────────────────────────────────────────

    private function buildSpBlock(ServiceProvider $sp, Tenant $tenant): string
    {
        $entityId = addslashes($sp->getEntityId());
        $name     = addslashes($sp->getDisplayName());
        $acsUrl   = trim((string) ($sp->getAcsUrl() ?? ''));
        $sloUrl   = trim((string) ($sp->getSloUrl() ?? ''));

        if ($acsUrl === '') {
            $this->logger->warning('Skipping SP metadata block without ACS URL', [
                'entity_id' => $sp->getEntityId(),
                'tenant' => $tenant->getSlug(),
            ]);

            return <<<PHP
// Skipped SP {$name} ({$entityId}) because no AssertionConsumerService URL is configured.
PHP;
        }

        // Attribute release
        $attrs = $sp->getAttributeReleaseOverride()
            ?? ($tenant->getAttributeReleasePolicy()['default'] ?? null)
            ?? $this->getDefaultAttributes($tenant);

        $attrsPhp = $this->phpArrayLiteral($attrs);

        $nameIdFormat = addslashes($sp->getNameIdFormat());
        $acsUrlEscaped = addslashes($acsUrl);
        $sloSection = '';
        if ($sloUrl !== '') {
            $sloUrlEscaped = addslashes($sloUrl);
            $sloSection = <<<PHP
    'SingleLogoutService' => [
        [
            'Binding'   => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location'  => '{$sloUrlEscaped}',
        ],
    ],
PHP;
        }

        // Certificate handling
        $certLine = '';
        if ($sp->getCertificate()) {
            $cert     = addslashes($sp->getCertificate());
            $certLine = "'certData' => '{$cert}',";
        }

        $encryptLine = $sp->isEncryptAssertions()
            ? "'assertion.encryption' => true,"
            : "'assertion.encryption' => false,";

        return <<<PHP
\$metadata['{$entityId}'] = [
    // SP: {$name}
    'AssertionConsumerService' => [
        [
            'Binding'   => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location'  => '{$acsUrlEscaped}',
            'index'     => 1,
        ],
    ],
{$sloSection}
    'NameIDFormat'     => '{$nameIdFormat}',
    {$certLine}
    {$encryptLine}
    'sign.authnrequest' => true,
    'attributes'       => {$attrsPhp},
    'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
    'authproc'         => [],
];
PHP;
    }

    /**
     * SimpleSAMLphp remote metadata is keyed globally by entityID, so later
     * duplicate blocks overwrite earlier ones. Prefer the most complete row.
     *
     * @param ServiceProvider[] $serviceProviders
     *
     * @return ServiceProvider[]
     */
    private function deduplicateServiceProviders(array $serviceProviders): array
    {
        $selected = [];

        foreach ($serviceProviders as $serviceProvider) {
            $entityId = trim($serviceProvider->getEntityId());
            if ($entityId === '') {
                continue;
            }

            $current = $selected[$entityId] ?? null;
            if ($current === null || $this->scoreServiceProvider($serviceProvider) > $this->scoreServiceProvider($current)) {
                if ($current !== null) {
                    $this->logger->warning('Replacing duplicate SP metadata entry with better candidate.', [
                        'entity_id' => $entityId,
                        'kept_source' => $serviceProvider->getSource(),
                        'replaced_source' => $current->getSource(),
                        'kept_tenant' => $serviceProvider->getTenant()?->getSlug(),
                        'replaced_tenant' => $current->getTenant()?->getSlug(),
                    ]);
                }

                $selected[$entityId] = $serviceProvider;
            }
        }

        uasort($selected, static fn (ServiceProvider $left, ServiceProvider $right): int => strcmp(
            $left->getDisplayName(),
            $right->getDisplayName()
        ));

        return array_values($selected);
    }

    private function scoreServiceProvider(ServiceProvider $serviceProvider): int
    {
        $score = 0;

        $sourceScore = match ($serviceProvider->getSource()) {
            ServiceProvider::SOURCE_MANUAL => 1000,
            ServiceProvider::SOURCE_EDUGAIN => 500,
            ServiceProvider::SOURCE_METADATA => 250,
            default => 0,
        };

        $score += $sourceScore;
        $score += $this->hasValue($serviceProvider->getAcsUrl()) ? 200 : 0;
        $score += $this->hasValue($serviceProvider->getSloUrl()) ? 100 : 0;
        $score += $this->hasValue($serviceProvider->getCertificate()) ? 50 : 0;
        $score += $this->hasValue($serviceProvider->getName()) ? 25 : 0;
        $score += count($serviceProvider->getRequestedAttributes() ?? []) > 0 ? 10 : 0;

        return $score;
    }

    private function hasValue(?string $value): bool
    {
        return trim((string) $value) !== '';
    }

    private function buildLdapAuthSource(Tenant $tenant, string $name): string
    {
        $cfg = $tenant->getLdapConfig() ?? [];

        $host          = addslashes($cfg['host']          ?? 'ldap://localhost');
        $baseDn        = addslashes($cfg['base_dn']       ?? 'dc=example,dc=com');
        $bindDn        = addslashes($cfg['bind_dn']       ?? '');
        $bindPw        = addslashes($cfg['bind_password'] ?? '');
        $userAttr      = addslashes($cfg['user_attr']     ?? 'uid');
        $searchFilter  = addslashes($cfg['search_filter'] ?? '(&(objectClass=person)(%username%))');
        $dnPattern     = addslashes($cfg['dn_pattern']    ?? '');
        $timeout       = (int) ($cfg['timeout'] ?? 30);
        $startTls      = ($cfg['start_tls'] ?? false) ? 'true' : 'false';

        // Build attribute map
        $attrMapPhp = $this->phpArrayLiteral($cfg['attribute_map'] ?? [
            'uid'                         => ['uid'],
            'mail'                        => ['mail'],
            'cn'                          => ['cn'],
            'sn'                          => ['sn'],
            'givenName'                   => ['givenName'],
            'displayName'                 => ['displayName'],
            'eduPersonPrincipalName'      => ['eduPersonPrincipalName'],
            'eduPersonAffiliation'        => ['eduPersonAffiliation'],
            'eduPersonScopedAffiliation'  => ['eduPersonScopedAffiliation'],
            'eduPersonEntitlement'        => ['eduPersonEntitlement'],
            'schacHomeOrganization'       => ['schacHomeOrganization'],
        ]);

        return <<<PHP
    '{$name}' => [
        'ubuntunet:Ldap',
        'tenant_slug'       => '{$tenant->getSlug()}',
        'connection_string' => '{$host}',
        'encryption'        => '{$startTls}' === 'true' ? 'starttls' : 'none',
        'version'           => 3,
        'timeout'           => {$timeout},
        'referrals'         => false,

        'searchBase'        => '{$baseDn}',
        'searchFilter'      => '{$searchFilter}',
        'searchAttributes'  => false,
        'dnPattern'         => '{$dnPattern}',
        'attribute'         => '{$userAttr}',

        'username'          => '{$bindDn}',
        'password'          => '{$bindPw}',

        'attributes'        => {$attrMapPhp},
    ],
PHP;
    }

    private function buildSamlAuthSource(Tenant $tenant, string $name): string
    {
        $cfg = $tenant->getSamlUpstreamConfig() ?? [];

        $upstreamIdp    = addslashes($cfg['idp_entity_id']  ?? '');
        $metadataUrl    = addslashes($cfg['metadata_url']   ?? '');
        $discoUrl       = addslashes($cfg['discovery_url']  ?? '');

        if ($upstreamIdp === '' && $metadataUrl === '') {
            throw new \InvalidArgumentException(sprintf(
                'Tenant "%s" uses the SAML Proxy backend but has no upstream metadata URL or IdP entity ID configured.',
                $tenant->getSlug()
            ));
        }

        return <<<PHP
    '{$name}' => [
        'saml:SP',
        'entityID'       => null,   // use SSP's own entity ID
        'idp'            => '{$upstreamIdp}' ?: null,
        'discoURL'       => '{$discoUrl}' ?: null,
        'metadataURL'    => '{$metadataUrl}' ?: null,

        'privatekey'     => 'wildcard_certificate.key',
        'certificate'    => 'wildcard_certificate.crt',

        'sign.authnrequest' => true,
        'sign.logout'       => true,
    ],
PHP;
    }

    private function buildUserpassAuthSource(Tenant $tenant, string $name): string
    {
        // Builds a database-backed auth source using our custom ubuntunet module
        $slug = $tenant->getSlug();
        return <<<PHP
    '{$name}' => [
        'ubuntunet:DatabaseAuth',
        'tenant_slug' => '{$slug}',
    ],
PHP;
    }

    private function buildRadiusAuthSource(Tenant $tenant, string $name): string
    {
        $cfg    = $tenant->getRadiusConfig() ?? [];
        $server = addslashes($cfg['server'] ?? '127.0.0.1');
        $secret = addslashes($cfg['secret'] ?? '');
        $port   = (int) ($cfg['port'] ?? 1812);

        return <<<PHP
    '{$name}' => [
        'radius:Radius',
        'hostname' => '{$server}',
        'secret'   => '{$secret}',
        'port'     => {$port},
        'timeout'  => 30,
        'retries'  => 3,
        'realm'    => '',
        'nas_identifier' => '{$this->samlidpHostname}',
    ],
PHP;
    }

    private function writeTenantCert(Tenant $tenant): void
    {
        $slug    = $tenant->getSlug();
        $certPem = $tenant->getSigningCertificate();
        $keyPem  = $tenant->getSigningPrivateKey();

        if (empty($certPem) || empty($keyPem)) {
            // Fall back to wildcard cert
            return;
        }

        $normalizedCert = preg_replace('/\s+/', '', trim($certPem));

        // Write cert with headers
        $certFormatted  = "-----BEGIN CERTIFICATE-----\n";
        $certFormatted .= chunk_split($normalizedCert, 64, "\n");
        $certFormatted .= "-----END CERTIFICATE-----\n";

        $this->fs->dumpFile($this->sspCertDir . '/' . $slug . '.crt', $certFormatted);
        $this->fs->dumpFile($this->sspCertDir . '/' . $slug . '.pem', $keyPem);
        $this->normalizeOwnership(
            $this->sspCertDir . '/' . $slug . '.crt',
            $this->sspCertDir . '/' . $slug . '.pem',
        );
        $this->fs->chmod($this->sspCertDir . '/' . $slug . '.crt', 0644);
        $this->fs->chmod($this->sspCertDir . '/' . $slug . '.pem', 0600);
    }

    private function writePhpFile(string $path, string $content, string $tenantSlug): void
    {
        // Write to a temp file first, then atomic rename
        $tmp = $path . '.tmp.' . $tenantSlug . '.' . getmypid();
        $this->fs->dumpFile($tmp, $content);

        // Lightweight syntax validation. Requiring large generated metadata files can
        // exhaust memory because PHP executes all array assignments during validation.
        try {
            token_get_all($content, \TOKEN_PARSE);
        } catch (\ParseError $e) {
            $this->fs->remove($tmp);
            throw new \RuntimeException(
                sprintf('Generated PHP file has syntax errors for tenant %s: %s', $tenantSlug, $e->getMessage()),
                previous: $e,
            );
        }

        $this->fs->rename($tmp, $path, true);
        $this->normalizeOwnership($path);
        $this->logger->debug('Written SSP config file', ['path' => $path, 'tenant' => $tenantSlug]);
    }

    private function getDefaultAttributes(Tenant $tenant): array
    {
        $policy = $tenant->getAttributeReleasePolicy();
        return $policy['default'] ?? [
            'uid',
            'mail',
            'cn',
            'sn',
            'givenName',
            'displayName',
            'eduPersonPrincipalName',
            'eduPersonAffiliation',
            'eduPersonScopedAffiliation',
            'eduPersonTargetedID',
            'schacHomeOrganization',
        ];
    }

    private function phpArrayLiteral(array $arr): string
    {
        if (empty($arr)) {
            return '[]';
        }

        $items = [];
        foreach ($arr as $key => $value) {
            $renderedValue = $this->phpValueLiteral($value);

            if (is_int($key)) {
                $items[] = $renderedValue;
                continue;
            }

            $items[] = "'" . addslashes((string) $key) . "' => " . $renderedValue;
        }

        return '[' . implode(', ', $items) . ']';
    }

    private function phpValueLiteral(mixed $value): string
    {
        if (is_array($value)) {
            return $this->phpArrayLiteral($value);
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        if ($value === null) {
            return 'null';
        }

        return "'" . addslashes((string) $value) . "'";
    }

    private function now(): string
    {
        return (new \DateTimeImmutable())->format('Y-m-d H:i:s T');
    }

    private function count(array $arr): int
    {
        return count($arr);
    }

    /**
     * @param string[] $blocks
     */
    private function joinBlocks(array $blocks): string
    {
        return implode("\n\n", array_filter($blocks));
    }

    private function normalizeOwnership(string ...$paths): void
    {
        if (!function_exists('posix_geteuid') || posix_geteuid() !== 0) {
            return;
        }

        foreach ($paths as $path) {
            if (!file_exists($path)) {
                continue;
            }

            @chown($path, 'app');
            @chgrp($path, 'app');
        }
    }

    private function buildIdpHostedBlock(Tenant $tenant): string
    {
        $entityId = addslashes($tenant->getEntityId());
        $slug     = addslashes($tenant->getSlug());
        $certFile = $slug . '.crt';
        $keyFile  = $slug . '.pem';
        $authSourceName = 'idp-' . $slug;
        $ssoUrl = "https://{$slug}.{$this->samlidpHostname}/saml2/idp/SSOService.php";
        $sloUrl = "https://{$slug}.{$this->samlidpHostname}/saml2/idp/SingleLogoutService.php";

        $mfaOptions = match ($tenant->getMfaPolicy()) {
            'required' => "'requireMFA' => true,",
            'optional' => "'requireMFA' => false,",
            default    => '',
        };

        $metadata = $this->metadataProfileBuilder->build($tenant);
        $hostedUiInfo = $this->normalizeHostedUiInfo($metadata['ui_info'] ?? []);
        $hostedRegistrationInfo = $this->normalizeHostedRegistrationInfo($metadata['registration_info'] ?? []);
        $orgName = addslashes($metadata['organization_name']);
        $orgUrl  = addslashes($metadata['organization_url']);
        $contactSection = $metadata['contacts'] === []
            ? ''
            : "    'contacts' => " . $this->phpArrayLiteral($metadata['contacts']) . ",\n";
        $registrationInfoSection = $hostedRegistrationInfo === []
            ? ''
            : "    'RegistrationInfo' => " . $this->phpArrayLiteral($hostedRegistrationInfo) . ",\n";
        $discoHintsSection = $metadata['disco_hints'] === []
            ? ''
            : "    'DiscoHints' => " . $this->phpArrayLiteral($metadata['disco_hints']) . ",\n";

        return <<<PHP
\$metadata['{$entityId}'] = [
    'host'           => '{$slug}.{$this->samlidpHostname}',
    'privatekey'     => '{$keyFile}',
    'certificate'    => '{$certFile}',
    'metadata.sign.privatekey' => '{$keyFile}',
    'metadata.sign.certificate' => '{$certFile}',
    'auth'           => '{$authSourceName}',
    'scope'          => ['{$slug}.{$this->samlidpHostname}'],
    'entityid'       => '{$entityId}',
    'SingleSignOnService' => '{$ssoUrl}',
    'SingleLogoutService' => '{$sloUrl}',
    'signature.algorithm'         => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
    'metadata.sign.enable'        => true,
    'metadata.sign.algorithm'     => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
    'assertion.encryption'        => false,
    'SingleLogoutServiceBinding' => [
        'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
    ],
    'NameIDFormat'   => [
        'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
    ],
    'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
    'authproc' => [
        5 => [
            'class' => 'saml:PersistentNameID',
            'identifyingAttribute' => 'eduPersonPrincipalName',
        ],
        20 => [
            'class' => 'saml:PersistentNameID2TargetedID',
            'attribute' => 'eduPersonTargetedID',
            'nameId' => false,
        ],
        70 => [
            'class'   => 'core:AttributeLimit',
            'default' => {$this->phpArrayLiteral($this->getDefaultAttributes($tenant))},
        ],
        80 => [
            'class' => 'core:AttributeMap',
            'name2oid',
            '%duplicate',
        ],
    ],
    'OrganizationName'        => ['en' => '{$orgName}'],
    'OrganizationDisplayName' => ['en' => '{$orgName}'],
    'OrganizationURL'         => ['en' => '{$orgUrl}'],
{$contactSection}{$registrationInfoSection}    'UIInfo' => {$this->phpArrayLiteral($hostedUiInfo)},
{$discoHintsSection}
    {$mfaOptions}
];
PHP;
    }

    private function normalizeHostedRegistrationInfo(array $registrationInfo): array
    {
        if ($registrationInfo === []) {
            return [];
        }

        $normalized = [];

        if (!empty($registrationInfo['RegistrationAuthority']) && is_string($registrationInfo['RegistrationAuthority'])) {
            $normalized['authority'] = $registrationInfo['RegistrationAuthority'];
        }

        if (!empty($registrationInfo['RegistrationInstant']) && is_string($registrationInfo['RegistrationInstant'])) {
            $normalized['instant'] = $registrationInfo['RegistrationInstant'];
        }

        if (!empty($registrationInfo['RegistrationPolicy']) && is_array($registrationInfo['RegistrationPolicy'])) {
            $normalized['policies'] = $registrationInfo['RegistrationPolicy'];
        }

        return $normalized;
    }

    private function normalizeHostedUiInfo(array $uiInfo): array
    {
        if ($uiInfo === []) {
            return [];
        }

        if (!isset($uiInfo['Logo']) || !is_array($uiInfo['Logo'])) {
            return $uiInfo;
        }

        $uiInfo['Logo'] = array_map(function (mixed $logo): mixed {
            if (!is_array($logo)) {
                return $logo;
            }

            if (array_key_exists('width', $logo)) {
                $logo['width'] = (int) $logo['width'];
            }

            if (array_key_exists('height', $logo)) {
                $logo['height'] = (int) $logo['height'];
            }

            return $logo;
        }, $uiInfo['Logo']);

        return $uiInfo;
    }
}
